CREATE TABLE `furniture_items` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `asset_name` varchar(255) NOT NULL,
  `type` char(255) NOT NULL,
  `asset_id` int(11) NOT NULL,
  `tile_span_x` smallint(6) NOT NULL,
  `tile_span_y` smallint(6) NOT NULL,
  `stack_height` double NOT NULL,
  `can_stack` tinyint(1) NOT NULL,
  `can_walk` tinyint(1) NOT NULL,
  `can_sit` tinyint(1) NOT NULL,
  `can_lay` tinyint(1) NOT NULL,
  `can_recycle` tinyint(1) NOT NULL,
  `can_trade` tinyint(1) NOT NULL,
  `can_marketplace_sell` tinyint(1) NOT NULL,
  `can_inventory_stack` tinyint(1) NOT NULL,
  `can_gift` tinyint(1) NOT NULL,
  `interaction_type` varchar(255) DEFAULT NULL,
  `interaction_modes` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
